#ifndef LIB_SERVER_MANAGER_SERVER_MANAGER_TASK_H_
#define LIB_SERVER_MANAGER_SERVER_MANAGER_TASK_H_


void serverManagerTask(void *pvParameters);


#endif  // LIB_SERVER_MANAGER_SERVER_MANAGER_TASK_H_
