#ifndef LIB_SYSTEM_MANAGER_COMMANDS_UTILITY_COMMANDS_H_
#define LIB_SYSTEM_MANAGER_COMMANDS_UTILITY_COMMANDS_H_


void register_system_utility();


#endif  // LIB_SYSTEM_MANAGER_COMMANDS_UTILITY_COMMANDS_H_
