#ifndef LIB_REGULATOR_MANAGER_REGULATOR_MANAGER_TASK_H_
#define LIB_REGULATOR_MANAGER_REGULATOR_MANAGER_TASK_H_


void regulatorManagerTask(void *pvParameters);


#endif  // LIB_REGULATOR_MANAGER_REGULATOR_MANAGER_TASK_H_
