#ifndef LIB_SYSTEM_MANAGER_SYSTEM_MANAGER_TASK_H_
#define LIB_SYSTEM_MANAGER_SYSTEM_MANAGER_TASK_H_


void systemManagerTask(void *pvParameters);


#endif  // LIB_SYSTEM_MANAGER_SYSTEM_MANAGER_TASK_H_
